### ISSUE TITLE
Odometry, can we count on it (get it? Ha)

### ISSUE THREAD

**Issue by wmbelk** [Team2556/Crescendo#13]
Odometry (Should follow YAGSL's documentation where +x is forward, +y is left, and +theta is CCW) *Note that the xbox controller sticks are inverted, so verify the inputs from the controller are actually positive otherwise add a negative sign to the sticks in the TeleopDrive class)
 - [x] Set up Odometry course
 - [x] Create Odometry calibrating spreadsheet (put it in this repository!)
 - [x] calibrate Odometry

**Comment by NawaPlayz** [comment]
Odometry looked promising with a simple sanity test of driving in straight lines and measuring with a tape measure. It would likely be helpful to test motion over diagonals, rotating while moving, and driving over long distances. I suspect all rotational movement will be inaccurate after a certain speed due to the navx drifting so much. Creating a spreadsheet after running some simple tests could help with the optimization of paths in order to decrease drift.
