### ISSUE TITLE
Ensure drive works

### ISSUE THREAD

**Issue by adamjarv1s** [Team2556/Crescendo#4]
once we get robot make sure robot drives

**Comment by Adamisbad** [comment]
jacob u got this

**Comment by NawaPlayz** [comment]
## Get the robot driving
So, a few things that should be done for the robot to be functional and driving good. First is making sure the robot properly drives in robot-centric. This should include testing the odometry (robot x, y, and theta). Next is field-centric, which should ideally tell us how much the NavX is drifting. If it is an insane amount of drift then we can look into april tags always resetting the robot's position in order to compensate for the drift.

- [ ] Swerve Robot-Centric (Toggle from field-centric with the '() -> true' parameter in the RobotContainer for TeleopDrive)
- [ ] Odometry (Should follow YAGSL's documentation where +x is forward, +y is left, and +theta is CCW) *Note that the xbox controller sticks are inverted, so verify the inputs from the controller are actually positive otherwise add a negative sign to the sticks in the TeleopDrive class)
- [ ] Field-centric driving (Test the amount of drift the NavX has after calibrating it, verify the robot drives properly)
- [ ] Test pathplanner with functional swerve drive and see how the paths for a basic autonomous need to be tweaked.

**Comment by wmbelk** [comment]
Awesome Christian!!!
I experimented and converted this to an issue with sub-issues instead of just tasks (checklist). We need everyone to merge in single topic updates/fixes. Having individual tasks should help (in theory). I'll close this one to avoid duplication of the issue.
